name: CI - Main Quality Gate & Deploy

on:
  push:
    branches: [ main ]

jobs:
  quality-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # Checkout
      # -----------------------------
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -----------------------------
      # Setup
      # -----------------------------
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # -----------------------------
      # Sonar Scanner
      # -----------------------------
      - name: Install SonarScanner
        run: dotnet tool install dotnet-sonarscanner --tool-path .sonar

      - name: Sonar Begin
        run: |
          .sonar/dotnet-sonarscanner begin \
            /k:"trongnguyenbinh_OrderService_afb74bb9-e103-4874-944c-ed77f61d9464" \
            /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" \
            /d:sonar.qualitygate.wait=true \
            /d:sonar.ws.timeout=120

      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release

      - name: Test with coverage
        run: |
          dotnet test \
            --no-build \
            --configuration Release \
            --settings coverlet.runsettings

      - name: Sonar End
        run: |
          .sonar/dotnet-sonarscanner end \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      # -----------------------------
      # Trigger Jenkins (CHá»ˆ KHI PASS)
      # -----------------------------
      - name: Trigger Jenkins Deploy
        if: success()
        run: |
          curl -X POST \
            "${{ secrets.JENKINS_URL }}/job/legacy-order-deploy/build" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
